### ISSUE TITLE
Kick players in case of a faulty truncation when modifiers are active

### ISSUE THREAD

**Issue by timraay** [timraay/HLLLogUtilities#26]
HLL truncates player names longer than 20 characters. If the 20th character in a player's name is a space, the truncated name will end with a space, and this makes it impossible to get information about that player through the `playerinfo` RCON command. This information is vital however.

If you take the player's full, untruncated name I believe the command WILL work. And since we know their steamid, we can get this full name through the Steam API. So, when we do notice that one of the players has an invalid name, we query their full name from the API, and use that instead.

**Comment by timraay** [comment]
As a side note, we need to test how this behaves when the 20th char is a special character. For instance, the name `≡J≡i≡M≡b≡0≡n≡I≡u≡M 🍍` also causes issues. HLU doesn't account for pineapples either, so they will show up as `None` entirely.

**Comment by FlorianSW** [comment]
Did you check the assumption of the playerinfo working when the _full_ name is provided? 🤔

**Comment by timraay** [comment]
Yes, I'm pretty sure I have successfully tried that. I recall at some point mentioning that it was possible, and that ironically the only way to get the full name through RCON was through the playerinfo command.

**Comment by timraay** [comment]
Apparently neither is true
