### ISSUE TITLE
/Autosession Error

### ISSUE THREAD

**Issue by grahamecase** [timraay/HLLLogUtilities#34]
Hey Abu, 

![image](https://github.com/timraay/HLLLogUtilities/assets/30606100/d9970190-5f27-44cd-9dc4-7f6611b91c82)

when trying to use /autosession we get this issue

**Comment by timraay** [comment]
Hey hey. I've had a look and think I've been able to identify and resolve the issue at hand. Give it another go and let me know if it works now.

Fix that prevents this issue from occurring again is in commit #878cda5 and will be included in next release.

**Comment by grahamecase** [comment]
sorted. thanks so much
