### ISSUE TITLE
Unexpected Error when I try export logs

### ISSUE THREAD

**Issue by LEVELcat** [timraay/HLLLogUtilities#36]
When i try export logs from session "[#477] asfafs ([RUS] | Jager Group Server)"
It's throw unexpected error with message " '>' not supported between instances of 'NoneType' and 'int' "
![image](https://github.com/timraay/HLLLogUtilities/assets/68501903/4a1e2e41-956c-497f-a116-a396946b385d)

**Comment by timraay** [comment]
Hey, thanks for letting me know. Appears that's an edge case I forgot to account for. A fix for it will be included in the next release.
