### ISSUE TITLE
Cant Export Match

### ISSUE THREAD

**Issue by DerDreher** [timraay/HLLLogUtilities#41]
Hey guys,

I'm having problems exporting yesterday's SLB to our Greyhound Event Server. In the Discord, when I "activate" the export, the error number 104 appears. 

I have tried to create a simple log file.
- Bot started (via SSH)
- Entered the command /export logs in Discord (so that the list opens)
- Selected the match "[#104] AUTO_Tue_06_Aug_18.21 (Greyhounds Event#1 - Blue)".
- Enter
--> Error 104

A little side info. We have recently switched to Qonzer with our servers. When I edited them via /credentials edit there were already minor problems. Sometimes changed values were entered in another server. That was confusing. 

Two weeks ago I installed the latest version of your log tool but used the old database.

Greetz Rambo_GT

[log_issue.txt](https://github.com/user-attachments/files/16521012/log_issue.txt)

**Comment by timraay** [comment]
This is a bit of a strange error but leads me to believe you have another instance of the bot running elsewhere.

It changing another server's credentials is worrysome and I recall having fixed such an issue in the past, but I assume that could be that other, outdated version that is still running somewhere? When I recently tried it worked fine.

**Comment by DerDreher** [comment]
Oh dear, you were absolutely right. There were actually 4 bots running at the same time. I have already discovered the error in my scripts. Now the export works again. Many thanks for your help and the "food for thought" :D
