### ISSUE TITLE
Large exports can cause interactions to expire

### ISSUE THREAD

**Issue by SniperRus** [timraay/HLLLogUtilities#44]
hi!
Trying to deploy on my own server and test exporting logs from manual and auto sessions
![image](https://github.com/user-attachments/assets/acf3919f-0b82-42c1-9e04-6f681b09a4aa)
on a big timeframe i can't get a log nor scoreboard - it rises an error - the app doesn't respond, however smaller sessions works well

[hll_log_utils.txt](https://github.com/user-attachments/files/17122946/hll_log_utils.txt)

what it could be?

**Comment by timraay** [comment]
Discord expects a response within 3 seconds of the command being sent (unless explicitly deferred). This error implies that by the time the bot tries to respond, those 3 seconds have already passed, most likely because it is taking too long to read and process all of the logs.

**Comment by SniperRus** [comment]
it seems to me that it doesn't help. Request to a large session didn't work

**Comment by timraay** [comment]
Did you update?

**Comment by SniperRus** [comment]
> Did you update? 

```
sniper@docker:~/docker/HLLLogUtilities$ git status
HEAD detached at v2.2.10
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   Dockerfile
        modified:   config.ini
        modified:   docker-compose.yml

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .dockerignore

no changes added to commit (use "git add" and/or "git commit -a")

```
> Works fine on the public instance I host.

did you tested on a 300 min session? i thought that public bot available to use in our discord server has limitation for long sessions
