### ISSUE TITLE
RCON address can not be resolved

### ISSUE THREAD

**Issue by ChitoUnfmz** [timraay/HLLLogUtilities#47]
i tried to put the credentials for my rcon server but it says fail to connect i make sure that it is the correct address and password and the server indeed is online so i dont know what could be the issue

**Comment by timraay** [comment]
This is most certainly a firewall issue on your end. Please reach out to your provider. For HLU in particular or RCON in general, the RCON port needs to accept incoming TCP connections.

I've tried on two machines in different locations and using two different networks, and received a "Semaphore timeout period has expired" error on both.

**Comment by ChitoUnfmz** [comment]
cool thanks ima do that we use gportal for the server so i guess thats my provider? HLU i got it from here on github

**Comment by timraay** [comment]
Your game server provider (GSP), exactly.

**Comment by ChitoUnfmz** [comment]
thanks man
